### ISSUE TITLE
`*`と'/'だとわかりにくいので `×` と `÷`に表記を直す

### ISSUE THREAD

**Issue by trasta298** [hackathon-22spring15/mushikui-frontend#15]
`*`と'/'だとわかりにくいので `×` と `÷`に表記を直す
![image](https://user-images.githubusercontent.com/13024718/174319229-faf230b1-8611-4547-8437-cf85fbc61255.png)

**Comment by 20jun01** [comment]
1df7969db3ada3a3c1627cdc49d59670dfca2478
